### ISSUE TITLE
firewalld: ERROR: INVALID_NAME: '.' is not allowed in 'ca.andyholmes.Valent'

### ISSUE THREAD

**Issue by DodoLeDev** [andyholmes/valent#531]
### Current Behavior

Once installed, Valent makes the `firewalld` service crash **each time it is started**.
It causes a serious problem to the OS because **it renders the firewall completely unavailable**.

```
firewalld[3475]: ERROR: INVALID_NAME: '.' is not allowed in 'ca.andyholmes.Valent'
```
_See the backtrace below._

---

My hypothesis is that **the file name contains dots** (.) and it seems that firewalld doesn't like it…

We should simply rename the file to something like `Valent.xml`, `valent-connect.xml` or `valent-andyholmes.xml`

### Expected Behavior

Valent should provide a valid firewalld configuration file which allows it to open its specific ports without crashing the entire service :sweat_smile:

### Desktop

GNOME Shell

### Operating System

Endeavour OS - Linux 6.4.3-arch1-2

### Installed from

Built from source (Other)

### Version

nightly

### Logs

```shell
systemd[1]: Starting firewalld - dynamic firewall daemon...
systemd[1]: Started firewalld - dynamic firewall daemon.
firewalld[3475]: ERROR: Failed to load user configuration. Falling back to full stock configuration.
firewalld[3475]: ERROR: INVALID_NAME: '.' is not allowed in 'ca.andyholmes.Valent'
firewalld[3475]: Traceback (most recent call last):
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 649, in start
                                                          self._start()
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 599, in _start
                                                          self._start_load_stock_config()
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 414, in _start_load_stock_config
                                                          self._loader_services(config.FIREWALLD_SERVICES)
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 690, in _loader_services
                                                          obj = service_reader(filename, path)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/io/service.py", line 224, in service_reader
                                                          service.check_name(service.name)
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/io/io_object.py", line 103, in check_name
                                                          raise FirewallError(
                                                      firewall.errors.FirewallError: INVALID_NAME: '.' is not allowed in 'ca.andyholmes.Valent'
                                                      
                                                      During handling of the above exception, another exception occurred:
                                                      
                                                      Traceback (most recent call last):
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 654, in start
                                                          self._start_failsafe()
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 638, in _start_failsafe
                                                          self._start_load_stock_config()
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 414, in _start_load_stock_config
                                                          self._loader_services(config.FIREWALLD_SERVICES)
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/fw.py", line 690, in _loader_services
                                                          obj = service_reader(filename, path)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/io/service.py", line 224, in service_reader
                                                          service.check_name(service.name)
                                                        File "/usr/lib/python3.11/site-packages/firewall/core/io/io_object.py", line 103, in check_name
                                                          raise FirewallError(
                                                      firewall.errors.FirewallError: INVALID_NAME: '.' is not allowed in 'ca.andyholmes.Valent'
firewalld[3475]: ERROR: INVALID_NAME: '.' is not allowed in 'ca.andyholmes.Valent'
firewalld[3475]: ERROR: Failed to load full stock configuration. This likely indicates a system level issue, e.g. the firewall backend (nftables, iptables) is broken. All hope is lost. Exiting.
firewalld[3475]: ERROR: Raising SystemExit in run_server
systemd[1]: firewalld.service: Deactivated successfully.
```

### Screenshots

_This is not a graphical problem. The console log is sufficient._

**Comment by andyholmes** [comment]
Thanks for reporting, should be fixed in #532

**Comment by DodoLeDev** [comment]
Nyaahhh! I was opening a pull request! I was too slow :pensive:

![image](https://github.com/andyholmes/valent/assets/59477313/70b501bd-152d-47b7-ae36-8c963a60d0ac)
